algorithm: vcc
save_dir: ./saved_models/classic_cv
save_name: vcc_cifar10_100000
vcc_unlab_loss_weight: 0.0
vcc_lab_loss_weight: 5.0
vcc_only_supervised: True
resume: False
ema_m: 0.0
gpu: 4
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1024
num_train_iter: 102400
num_eval_iter: 2000
num_labels: 100000
batch_size: 64
eval_batch_size: 256
hard_label: True
T: 0.5
thresh_warmup: True
p_cutoff: 0.95
vcc_p_cutoff: 0.75
ulb_loss_ratio: 0.0
uratio: 1
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: vcc_wrn_28_2
vcc_z_dim: 64
vcc_training_warmup: 30000
vcc_selection_warmup: 50000
net_from_name: False
data_dir: ./data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 2
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10004
dist_backend: nccl
num_log_iter: 100
