algorithm: vcc
save_dir: ./saved_models/vcc_ssl_full/noisy_cifar10/vccflex
save_name: vccflex_noisy0.1_cifar10_40_4gpu
label_noise_ratio: 0.1
vcc_uncertainty_method: consistency
vcc_enc_norm: bn
vcc_dec_norm: bn
vcc_encoder_dims: [256, 64]
vcc_decoder_dims: [256, 64]
vcc_mc_sampling_times: 20
vcc_mc_keep_p: 0.7
vcc_disable_variance: False
resume: False
load_path: None
overwrite: False
use_tensorboard: True
vcc_training_warmup: 180000
vcc_selection_warmup: 360000
vcc_variance_warmup: 540000
vcc_lab_loss_weight: 0.0
vcc_unlab_recon_loss_weight: 2.0
vcc_unlab_kl_loss_weight: 2.0
vcc_z_dim: 16
vcc_p_cutoff: 0.95
epoch: 1024
num_train_iter: 1048576
save_interval: 50000
num_eval_iter: 1000
num_labels: 40
batch_size: 64
eval_batch_size: 256
hard_label: True
T: 0.5
thresh_warmup: True
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: vcc_wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
gpu: None
num_log_iter: 100