T: 0.5
algorithm: vcc
amp: false
batch_size: 64
clip: 0.0
crop_ratio: 0.875
data_dir: ./data
dataset: cifar10
dist_backend: nccl
dist_url: tcp://127.0.0.1:10001
ema_m: 0.999
epoch: 1024
eval_batch_size: 256
gpu: None
hard_label: true
img_size: 32
label_noise_ratio: 0.1
layer_decay: 1.0
load_path: None
lr: 0.03
momentum: 0.9
multiprocessing_distributed: true
net: vcc_wrn_28_2
net_from_name: false
num_classes: 10
num_eval_iter: 1000
num_labels: 250
num_log_iter: 100
num_train_iter: 1048576
num_workers: 1
optim: SGD
overwrite: false
p_cutoff: 0.95
rank: 0
resume: false
save_dir: ./saved_models/vcc_ssl_full/noisy_cifar10/vccflex
save_interval: 50000
save_name: vccflex_noisy0.1_cifar10_250_4gpu
seed: 0
thresh_warmup: true
train_sampler: RandomSampler
ulb_loss_ratio: 1.0
uratio: 7
use_cat: true
use_tensorboard: true
vcc_dec_norm: bn
vcc_decoder_dims:
- 256
- 64
vcc_disable_variance: false
vcc_enc_norm: bn
vcc_encoder_dims:
- 256
- 64
vcc_lab_loss_weight: 0.0
vcc_mc_keep_p: 0.7
vcc_mc_sampling_times: 20
vcc_p_cutoff: 0.95
vcc_selection_warmup: 360000
vcc_training_warmup: 180000
vcc_uncertainty_method: consistency
vcc_unlab_kl_loss_weight: 2.0
vcc_unlab_recon_loss_weight: 2.0
vcc_variance_warmup: 540000
vcc_z_dim: 16
weight_decay: 0.0005
world_size: 1
