algorithm: vcc
save_dir: ./saved_models/vcc_ssl_full/stl10/vccsim2
save_name: vcc_stl10_1000_4gpu
vcc_uncertainty_method: consistency
vcc_enc_norm: bn
vcc_dec_norm: bn
vcc_encoder_dims: [256, 64]
vcc_decoder_dims: [256, 64]
vcc_mc_sampling_times: 20
vcc_mc_keep_p: 0.7
vcc_disable_variance: True
resume: True
load_path: ./saved_models/vcc_ssl_full/stl10/vccsim/vcc_stl10_1000_4gpu/model_0000500000.pth
in_loss_ratio: 1.0
proj_size: 128
K: 256
da_len: 32
smoothing_alpha: 0.9
T: 0.1
vcc_training_warmup: 180000
vcc_selection_warmup: 360000
vcc_variance_warmup: 540000
vcc_lab_loss_weight: 0.0
vcc_unlab_recon_loss_weight: 2.0
vcc_unlab_kl_loss_weight: 2.0
vcc_z_dim: 16
vcc_p_cutoff: 0.95
overwrite: False
use_tensorboard: True
epoch: 1024
num_train_iter: 1048576
save_interval: 50000
num_eval_iter: 1000
num_labels: 1000
batch_size: 64
eval_batch_size: 256
hard_label: True
thresh_warmup: True
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 96
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: vcc_wrn_var_37_2
net_from_name: False
data_dir: ./data
dataset: stl10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10002
dist_backend: nccl
gpu: None
num_log_iter: 100