K: 256
T: 0.1
algorithm: simmatch
amp: false
batch_size: 64
clip: 0.0
crop_ratio: 0.875
da_len: 32
data_dir: ./data
dataset: cifar10
dist_backend: nccl
dist_url: tcp://127.0.0.1:10056
ema_m: 0.999
epoch: 1024
eval_batch_size: 256
gpu: None
img_size: 32
in_loss_ratio: 1.0
label_noise_ratio: 0.1
layer_decay: 1.0
load_path: None
lr: 0.03
momentum: 0.9
multiprocessing_distributed: true
net: wrn_28_2
net_from_name: false
num_classes: 10
num_eval_iter: 1000
num_labels: 250
num_log_iter: 100
num_train_iter: 1048576
num_workers: 1
optim: SGD
overwrite: false
p_cutoff: 0.95
proj_size: 128
rank: 0
resume: false
save_dir: ./saved_models/vcc_ssl_full/noisy_cifar10/simmatch
save_interval: 50000
save_name: simmatch_noisy0.1_cifar10_250_4gpu
seed: 0
smoothing_alpha: 0.9
train_sampler: RandomSampler
ulb_loss_ratio: 1.0
uratio: 7
use_cat: true
use_tensorboard: true
weight_decay: 0.0005
world_size: 1
